/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavouryRouteImport } from './routes/savoury'
import { Route as SweetRouteImport } from './routes/sweet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavouryRoute = SavouryRouteImport.update({
  id: '/savoury',
  path: '/savoury',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetRoute = SweetRouteImport.update({
  id: '/sweet',
  path: '/sweet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/savoury': typeof SavouryRoute
  '/sweet': typeof SweetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/savoury': typeof SavouryRoute
  '/sweet': typeof SweetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/savoury': typeof SavouryRoute
  '/sweet': typeof SweetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/savoury' | '/sweet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/savoury' | '/sweet'
  id: '__root__' | '/' | '/savoury' | '/sweet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavouryRoute: typeof SavouryRoute
  SweetRoute: typeof SweetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savoury': {
      id: '/savoury'
      path: '/savoury'
      fullPath: '/savoury'
      preLoaderRoute: typeof SavouryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet': {
      id: '/sweet'
      path: '/sweet'
      fullPath: '/sweet'
      preLoaderRoute: typeof SweetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavouryRoute: SavouryRoute,
  SweetRoute: SweetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
